// Package render transforme un manifeste en artefacts : units systemd
// (templates statiques + un .target par session) et fichiers d'environnement
// par instance. Les units générés ne s'éditent jamais à la main.
package render

import (
	"embed"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/AudioLibreLab/stompbox/internal/manifest"
)

//go:embed templates/*
var tmplFS embed.FS

// File est un artefact généré. Path est relatif à ~/.config :
// "systemd/user/..." pour les units, "stompbox/..." pour les fichiers d'env.
type File struct {
	Path    string
	Content string
}

// Render produit l'ensemble des artefacts du manifeste, triés par chemin.
func Render(m *manifest.Manifest) ([]File, error) {
	var files []File

	// Gabarits de service statiques, embarqués dans le binaire.
	entries, err := tmplFS.ReadDir("templates")
	if err != nil {
		return nil, err
	}
	for _, e := range entries {
		data, err := tmplFS.ReadFile("templates/" + e.Name())
		if err != nil {
			return nil, err
		}
		files = append(files, File{
			Path:    "systemd/user/" + e.Name(),
			Content: string(data),
		})
	}

	for _, sName := range m.SessionNames() {
		s := m.Sessions[sName]

		// Un .target par session : Wants= (pas Requires=, une app qui
		// plante ne doit pas faire échouer toute la session), pas de
		// section [Install] (démarrage purement impératif).
		var units []string
		for _, a := range s.Apps {
			units = append(units, a.Unit())
		}
		if s.Patchbay != nil {
			units = append(units, "qpwgraph@"+sName+".service")
		}
		files = append(files, File{
			Path: "systemd/user/" + sName + ".target",
			Content: fmt.Sprintf(`# Generated by stompbox — DO NOT EDIT.
[Unit]
Description=Stompbox session "%s"
Wants=%s
`, sName, strings.Join(units, " ")),
		})

		// Un fichier d'env par instance.
		for _, a := range s.Apps {
			f, err := envFile(m, a)
			if err != nil {
				return nil, fmt.Errorf("session %q: app %q: %w", sName, a.Name, err)
			}
			files = append(files, f)
		}
		if s.Patchbay != nil {
			exclusive := ""
			if s.Patchbay.Exclusive {
				exclusive = "-x"
			}
			files = append(files, File{
				Path: "stompbox/qpwgraph/" + sName + ".env",
				Content: envContent(
					kv{"QPW_PATCHBAY", m.Resolve(s.Patchbay.File)},
					kv{"QPW_EXCLUSIVE", exclusive},
				),
			})
		}
	}

	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	return files, nil
}

// CheckPaths signale les fichiers référencés par le manifeste qui n'existent
// pas encore sur le disque (presets, songs, patchbays…). Non bloquant :
// l'utilisateur peut générer les units avant d'avoir créé ses presets.
func CheckPaths(m *manifest.Manifest) []string {
	var warnings []string
	check := func(ctx, p string) {
		if p == "" {
			return
		}
		abs := m.Resolve(p)
		if _, err := os.Stat(abs); err != nil {
			warnings = append(warnings, fmt.Sprintf("%s: fichier introuvable: %s", ctx, abs))
		}
	}
	for _, sName := range m.SessionNames() {
		s := m.Sessions[sName]
		for _, a := range s.Apps {
			ctx := sName + "/" + a.Name
			check(ctx, a.Preset)
			check(ctx, a.Song)
			check(ctx, a.Session)
			check(ctx, a.MIDIBinding)
		}
		if s.Patchbay != nil {
			check(sName+"/patchbay", s.Patchbay.File)
		}
	}
	return warnings
}

type kv struct {
	k, v string
}

// envContent produit un fichier EnvironmentFile= systemd. Les valeurs sont
// systématiquement entre guillemets (chemins avec espaces).
func envContent(pairs ...kv) string {
	var b strings.Builder
	b.WriteString("# Generated by stompbox — DO NOT EDIT.\n")
	for _, p := range pairs {
		fmt.Fprintf(&b, "%s=%q\n", p.k, p.v)
	}
	return b.String()
}

func envFile(m *manifest.Manifest, a *manifest.App) (File, error) {
	switch a.Kind {
	case manifest.KindCarla:
		pairs := []kv{
			{"CARLA_PRESET", m.Resolve(a.Preset)},
		}
		if a.OSCTCPPort != 0 {
			// Variable lue directement par Carla : active son serveur OSC TCP.
			pairs = append(pairs, kv{"CARLA_OSC_TCP_PORT", fmt.Sprint(a.OSCTCPPort)})
		}
		return File{Path: "stompbox/carla/" + a.Name + ".env", Content: envContent(pairs...)}, nil

	case manifest.KindHydrogen:
		return File{
			Path:    "stompbox/hydrogen/" + a.Name + ".env",
			Content: envContent(kv{"H2_SONG", m.Resolve(a.Song)}),
		}, nil

	case manifest.KindSooperLooper:
		var extra []string
		if a.Session != "" {
			extra = append(extra, "-L", m.Resolve(a.Session))
		}
		if a.MIDIBinding != "" {
			extra = append(extra, "-m", m.Resolve(a.MIDIBinding))
		}
		return File{
			Path: "stompbox/sooperlooper/" + a.Name + ".env",
			Content: envContent(
				kv{"SL_OSC_PORT", fmt.Sprint(a.OSCPort)},
				kv{"SL_LOOPS", fmt.Sprint(a.Loops)},
				kv{"SL_CHANNELS", fmt.Sprint(a.Channels)},
				kv{"SL_LOOPTIME", fmt.Sprint(a.LoopTime)},
				kv{"SL_EXTRA_ARGS", strings.Join(extra, " ")},
			),
		}, nil
	}
	return File{}, fmt.Errorf("kind %q inconnu", a.Kind)
}
